/**
 * Per-bodytype sprite render-buffer correction. AUTO-GENERATED by
 * scripts/measureSprite.mjs (`node scripts/measureSprite.mjs --emit`).
 * DO NOT EDIT BY HAND — re-run the generator after adding/replacing a sprite.
 *
 * THE HARD RULE: a sprite is sized so its solid BODY pixels (alpha-trimmed
 * AND mirror-excluded) fill the GT4 length x width footprint. widthMult =
 * 1 + (mirror ear inflation %), so protruding door-mirrors land just OUTSIDE
 * L x W and the body spans W (= GT4 `wid`, which is mirrors-excluded per
 * ISO 612 sec 6.2). lengthMult is always 1.000 (length needs no correction).
 * widthMult is clamped to [1.00, 1.20]; out-of-band values fall back to
 * 1.000 and are flagged for hand-tuning. Motorcycles get [1.000, 1.000]
 * (handlebars ARE the width). Collision/physics dims in CAR().size are
 * UNCHANGED — only the drawImage destination rect is scaled.
 *
 * Tuple format: [lengthMultiplier, widthMultiplier].
 */
export const SPRITE_BUFFER: Record<string, readonly [number, number]> = {
  sedan:            [1.000, 1.107],
  civic99:          [1.000, 1.108],
  accord99:         [1.000, 1.151],
  hatch:            [1.000, 1.141],
  suv:              [1.000, 1.141],
  pickup:           [1.000, 1.193],
  silvia:           [1.000, 1.137],
  silvia_180sx:     [1.000, 1.120],
  civic_eg:         [1.000, 1.131],
  ae86:             [1.000, 1.130],
  rx7_fc:           [1.000, 1.103],
  rx7_fd:           [1.000, 1.118],
  kawasaki_ninja:   [1.000, 1.000],  // bike: full box (handlebars = width)
  honda_cb500:      [1.000, 1.000],  // bike: full box (handlebars = width)
  suzuki_bandit:    [1.000, 1.000],  // bike: full box (handlebars = width)
  suzuki_katana:    [1.000, 1.000],  // bike: full box (handlebars = width)
  gtr_r34:          [1.000, 1.118],
  gtr_r34_vspec:    [1.000, 1.097],
  nsx_na:           [1.000, 1.150],
  miata_na:         [1.000, 1.141],
  towtruck:         [1.000, 1.180],
  semi_truck:       [1.000, 1.146],
  semi:             [1.000, 1.146],
  box_truck:        [1.000, 1.093],
  boxtruck:         [1.000, 1.093],
  cruiser:          [1.000, 1.151],
  ambulance:        [1.000, 1.140],
  dodge_viper:      [1.000, 1.057],
  plymouth_cuda:    [1.000, 1.029],
  dodge_charger:    [1.000, 1.043],
  audi_quattro:     [1.000, 1.125],
  dodge_super_bee:  [1.000, 1.034],
  ruf_btr:          [1.000, 1.089],
  ruf_ctr_yb:       [1.000, 1.075],
  ruf_ctr2:         [1.000, 1.079],
};

export const SPRITE_CACHE_LONG_AXIS = 512;
