// OSM-B: emit a game TS module from the built candidate rows (a class-tier slice).
//
//   node tools/osm/emit.mjs [tier]
//
// tier: 'highways' (default — motorway/trunk + their ramps) or 'arterials'
//       (adds primary + primary ramps; requires the spatial index first).
//
// Reads  fixtures/osm/charlotte_rows.json (tools/osm/build.mjs)
// Writes src/config/world/osmCharlotte.ts
//
// Data © OpenStreetMap contributors, ODbL.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const tier = process.argv[2] ?? 'highways';
const KEEP = {
  highways: ['motorway', 'trunk', 'motorway_link', 'trunk_link'],
  arterials: ['motorway', 'trunk', 'primary', 'motorway_link', 'trunk_link', 'primary_link'],
  full: null, // every class the builder kept
}[tier];
if (KEEP === undefined) throw new Error(`unknown tier ${tier}`);

const { meta, rows, props, intersections } = JSON.parse(
  readFileSync(join(ROOT, 'fixtures', 'osm', 'charlotte_rows.json'), 'utf8'));

const keptIdx = [];
for (let i = 0; i < rows.length; i++) if (!KEEP || KEEP.includes(props[i].class)) keptIdx.push(i);
const keptRows = keptIdx.map((i) => rows[i]);
const keptProps = keptIdx.map((i) => props[i]);

// Keep only intersections within 6 tiles of a kept row's polyline (others
// would never find a crossing on this tier and are dead weight).
const SNAP = 6;
function nearRow(x, y) {
  for (const r of keptRows) {
    // cheap bbox first
    let minx = Infinity, miny = Infinity, maxx = -Infinity, maxy = -Infinity;
    for (let k = 4; k < r.length; k += 2) {
      if (r[k] < minx) minx = r[k]; if (r[k] > maxx) maxx = r[k];
      if (r[k + 1] < miny) miny = r[k + 1]; if (r[k + 1] > maxy) maxy = r[k + 1];
    }
    if (x < minx - SNAP || x > maxx + SNAP || y < miny - SNAP || y > maxy + SNAP) continue;
    for (let k = 4; k < r.length - 2; k += 2) {
      const ax = r[k], ay = r[k + 1], bx = r[k + 2], by = r[k + 3];
      const dx = bx - ax, dy = by - ay;
      const l2 = dx * dx + dy * dy;
      let t = l2 ? ((x - ax) * dx + (y - ay) * dy) / l2 : 0;
      t = Math.max(0, Math.min(1, t));
      const d2v = (x - (ax + dx * t)) ** 2 + (y - (ay + dy * t)) ** 2;
      if (d2v <= SNAP * SNAP) return true;
    }
  }
  return false;
}
const keptIsect = intersections.filter((r) => nearRow(r[7], r[8]));

// Spawn: on the longest I-485 row, at its midpoint vertex, heading along the row.
let spawnRow = null, spawnLen = -1;
for (const r of keptRows) {
  if (!String(r[2]).startsWith('I-485')) continue;
  let L = 0;
  for (let k = 4; k < r.length - 2; k += 2) L += Math.hypot(r[k + 2] - r[k], r[k + 3] - r[k + 1]);
  if (L > spawnLen) { spawnLen = L; spawnRow = r; }
}
if (!spawnRow) spawnRow = keptRows[0];
const nPts = (spawnRow.length - 4) / 2;
const mi = 4 + 2 * Math.floor(nPts / 2);
const sx = spawnRow[mi], sy = spawnRow[mi + 1];
const hx = spawnRow[mi + 2] - spawnRow[mi], hy = spawnRow[mi + 3] - spawnRow[mi + 1];
const spawnAngle = Math.atan2(hy, hx);

const verts = keptRows.reduce((s, r) => s + (r.length - 4) / 2, 0);
const byClass = {};
for (const p of keptProps) byClass[p.class] = (byClass[p.class] ?? 0) + 1;
console.log(`tier=${tier}: ${keptRows.length} rows, ${verts} verts, ${keptIsect.length} intersections`);
console.log(byClass);
console.log(`spawn on "${spawnRow[2]}" @ ${sx},${sy} angle ${spawnAngle.toFixed(3)}`);

const lines = [];
lines.push('// GENERATED by tools/osm/emit.mjs — do not hand-edit (re-run the tool).');
lines.push('// Charlotte, NC road network derived from OpenStreetMap.');
lines.push('// Data © OpenStreetMap contributors, licensed under ODbL 1.0.');
lines.push('// User-visible attribution is REQUIRED before store ship.');
lines.push(`// tier=${tier}: ${keptRows.length} rows / ${verts} verts / ${keptIsect.length} authored intersections.`);
lines.push(`// Projection: 1:${meta.scaleDiv} layout, center ${meta.center.map((v) => v.toFixed(4)).join(',')}, ${meta.mPerTile.toFixed(3)} m/tile.`);
lines.push('');
lines.push("import type { BaselineRoadRow } from './baselineRoads';");
lines.push('');
lines.push('export const OSM_CLT_ROWS: BaselineRoadRow[] = [');
for (const r of keptRows) lines.push(JSON.stringify(r) + ',');
lines.push('];');
lines.push('');
lines.push('// [\'isect\', control(0-4), la0,la1,la2,la3, turnMask, x, y] — see intersectionSchema.ts');
lines.push('export const OSM_CLT_INTERSECTIONS: (string | number)[][] = [');
for (const r of keptIsect) lines.push(JSON.stringify(r) + ',');
lines.push('];');
lines.push('');
lines.push(`export const OSM_CLT_SPAWN_TILE: [number, number] = [${sx}, ${sy}];`);
lines.push(`export const OSM_CLT_SPAWN_ANGLE = ${spawnAngle.toFixed(4)};`);
lines.push('');

const out = lines.join('\n');
writeFileSync(join(ROOT, 'src', 'config', 'world', 'osmCharlotte.ts'), out);
console.log(`wrote src/config/world/osmCharlotte.ts (${(out.length / 1024).toFixed(0)} KB)`);
